flex_array: fix flex_array_put_ptr() for non-lvalue ptr
when the @ptr is NULL or something else which is not lvalue,
we will get this error when compile it:

error: lvalue required as unary ‘&’ operand

Signed-off-by: Lai Jiangshan <laijs@cn.fujitsu.com>